services:
  - type: web
    name: my-web-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: DATABASE_URL
        value: 'your_database_url'
      - key: PORT
        value: '3000'
